language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install:
  - pip install -r dev-requirements.txt
  - pip install .

script:
  # coverage >= 4 does not support Python 3.2
  - if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then python test.py; else coverage run test.py; fi

after_success:
  - codecov
  - coveralls
